import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { Providers } from "@/providers";

const inter = Inter({
    display: "swap",
    subsets: ["latin"],
});

// TODO: Setup SEO
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("relative antialiased", inter.className)}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
