import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { Providers } from "@/providers";

const darkerGrotesque = Darker_Grotesque({
    display: "swap",
    subsets: ["latin"],
    variable: "--font-darkerGrotesque",
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// TODO: Setup SEO
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "font-darkerGrotesque relative overflow-x-hidden antialiased",
                    darkerGrotesque.variable,
                )}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
